classdef Dependencies < phutils.mixins.HasDependencies
    %databrowser.Dependencies  Defines the dependencies for DataBrowser
    properties ( Constant )
        DEPENDENCIES = {...
            phutils.dependencies.GLTDependency, ...
            phutils.dependencies.Dependency(...
                'SICMtoolbox',...
                'TestCallback',@()(~~exist('SICM.SICMScan','class')),...
                'HelpCallback',@()('The SICM toolbox is required. Get it from Patrick.'),...
                'Critical',false, 'Silent',true...
            ),...
            phutils.dependencies.Dependency(...
                'Bioformat toolbox',...
                'TestCallback',@()(~~exist('bfopen','file')),...
                'HelpCallback',@()('The Bioformat toolbox is required to open msr files. Get it from https://www.openmicroscopy.org/bio-formats/downloads/'),...
                'Critical',false, 'Silent',true...
            ), ...
            phutils.dependencies.MatlabReleaseDependency(2018,'a')...
        }
    end
end