function addLayout(self)
%ADDLAYOUT   Adds the layout components

    self.Layout = uix.HBox(...
        'Parent', self.Figure);
    
    lbuttons = uix.HButtonBox(...
        'Parent',self.Layout, ...
        'ButtonSize', [32 32] ...
    );
    
    grid = uix.Grid(...
        'Parent',self.Layout,...
        'Padding',5 ...
    );
    
    rbuttons = uix.HButtonBox(...
        'Parent', self.Layout, ...
        'ButtonSize',[32 32] ...
    );
    
    
    for i = 1:8
        self.AxesCollection{i} = databrowser.PreviewField(...
            'Parent', grid ...
        );
    end
    
    grid.Widths = [-1 -1 -1 -1];
    grid.Heights = [-1 -1];
    
    
    l1 = uicontrol(lbuttons, ...
        'String', '<', ...
        'Callback', @(evt, src)self.shift(-1) ...
    );
    l2 = uicontrol(lbuttons, ...
        'String', '<<', ...
        'Callback', @(evt, src)self.shift(-numel(grid.Widths) * numel(grid.Heights)) ...
    ); 

    r2 = uicontrol(rbuttons, ...
        'String', '>>', ...
        'Callback', @(evt, src)self.shift(numel(grid.Widths) * numel(grid.Heights)) ...
    );
    r1 = uicontrol(rbuttons, ...
        'String', '>', ...
        'Callback', @(evt, src)self.shift(1) ...
    );

    self.Layout.Widths=[72,-1,72];