function addListeners( self )
%ADDLISTENERS  adds the listeners for changes in the data

    self.LoadListeners.IsReady = self.Model.addlistener(...
        'IsReady', 'PostSet', @(src,evt)(self.show()));
    
    self.LoadListeners.CurrentMsg = self.Model.addlistener(...
        'CurrentMsg', 'PostSet', @(src, evt)(...
            set(self.SplashProgressBars.Minor, 'Label', evt.AffectedObject.(src.Name))...
        )...
    );
    
    self.LoadListeners.SubFraction = self.Model.addlistener(...
        'SubFraction',...
        'PostSet', @(src, evt)(...
            set(self.SplashProgressBars.Minor, 'Fraction', evt.AffectedObject.(src.Name))...
        )...
    );% , self.Model.SubFraction)));
        
    
    
    self.LoadListeners.TotalFraction = self.Model.addlistener(...
        'TotalFraction',...
        'PostSet', @(src, evt)(...
            set(self.SplashProgressBars.Major, 'Fraction', evt.AffectedObject.(src.Name))...
        )...
    );