function addMenu( self )
%ADDMENU adds the menubar to the Gui.
    
    self.Menu.Quit = uimenu(...
        'Text','Quit',...
        'MenuSelectedFcn', @(~,~)self.Controller.close(), ...
        'Tag', 'MenuQuit', ...
        'Parent', self.Figure...
    );
    
    self.Menu.Settings = uimenu(...
        'Text','Settings',...
        'MenuSelectedFcn', @(src,evt)self.Controller.getSettings(), ...
        'Tag', 'MenuSettings', ...
        'Parent', self.Figure);
